#
# MPM listener configuration file
#
# This configuration file is only used by the docker image.
#

spring:
  kafka:
    listener:
      concurrency: 5
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
    web-application-type: none
  datasource:
    url: jdbc:mysql://batch-db:3306/batch
    username: admin
    password: ENC(DtIzGPj615i3oxA5xbW+5G5Pf40SrKfCmRDe962SHB5lw9aBR+zdqiylP1Nzt329)
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  jackson:
    serialization:
      write_dates_as_timestamps: false

mbm:
  listener:
    server: batch-listener
  scheduler:
    server: batch-scheduler

# Kafka configuration.
# bootstrapAddress: Kafka server URL.
# maxRequestSize: Maximal request size (default: 4MB).
# retentionDays: Number of days the logs are kept.
# deletionDays: Number of days after which the logs are deleted.
# topic: Apache Kafka topic name.
kafka:
  bootstrapAddress: batch-kafka:9092
  maxRequestSize: 4194304
  retentionDays: 1
  deletionDays: 1
  active: true
  jobLogging:
    offsetReset: latest
    topic: batchJobExecutionLog
    partitions: 5
    replicas: 1
    level: DEBUG
  jobStatus:
    offsetReset: latest
    topic: batchJobStatus
    partitions: 5
    replicas: 1
  agentStatus:
    offsetReset: latest
    topic: batchAgentStatus
    group: batchmanager
    partitions: 5
    replicas: 1
  agentScheduler:
    offsetReset: latest
    topic: batchAgentScheduler
    group: batchmanager
    partitions: 5
    replicas: 1
