# General spring configurations
spring:
  # Spring main configurations
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  # JPA configurations
  jpa:
    show-sql: false
    hibernate:
      enable_lazy_load_no_trans: true
  # Spring batch configurations
  batch:
    initialize-schema: never
  # JSON configurations
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# DB2 configuration
db2prod:
  datasource:
    jdbc-url: jdbc:db2://kswfosa0.hlcl.com:5021/DEHALODDFAP:currentSchema=DB2PROD;allowNextOnExhaustedResultSet=2;
    username: vogtjn
    password: Dilbertc
    driverClassName: com.ibm.db2.jcc.DB2Driver

db2deve:
  datasource:
    jdbc-url: jdbc:db2://kswfosb0.hlcl.com:5041/DEHALODDFAT:currentSchema=DEVELOP;allowNextOnExhaustedResultSet=2;
    username: vogtjn
    password: Dilbertc
    driverClassName: com.ibm.db2.jcc.DB2Driver

# Batch Kafka configuration
# bootstrapAddress: Kafka server URL
# maxRequestSize: Maximal request size (default: 4MB)
# retentionDays: Number of days the logs are kept
# deletionDays: Number of days after which the logs are deleted
# job: Job message configuration
# step: Step message configuration
# chunk: Step message configuration
# control: Start/stop message configuration
kafka:
  bootstrapAddress: localhost:9090
  maxRequestSize: 4194304
  retentionDays: 1
  deletionDays: 1
  job:
    topic: batchJobExecution
    partitions: 1
    replicas: 1
  step:
    topic: batchStepExecution
    partitions: 1
    replicas: 1
  chunk:
    topic: batchChunkExecution
    partitions: 1
    replicas: 1
  control:
    topic: batchControl
    partitions: 1
    replicas: 1

