#
# MPM listener configuration file.
#
# This configuration file is only used by the docker image.
#

#
# Spring configuration
#
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://batch-db:3306/batch
    username: admin
    password: ENC(DtIzGPj615i3oxA5xbW+5G5Pf40SrKfCmRDe962SHB5lw9aBR+zdqiylP1Nzt329)
    driver-class-name: com.mysql.cj.jdbc.Driver

#
# Server configuration
#
server:
  address: 0.0.0.0
  port: 8090

#
# MBM configuration
#
mbm:
  library:
    jobs: ./jobs
  listener:
    server: batch-listener
  scheduler:
    server: batch-scheduler
  server:
    host: localhost
    port: 8090
    jwt:
      secret: mU*mJxJ*&31p
  ldap:
    server: ldapd-rw.hlcl.com
    port: 1391
  mail:
    server: smtp.gmail.com

#
# Kafka configuration.
#   bootstrapAddress: Kafka server URL.
#   maxRequestSize: Maximal request size (default: 4MB).
#   retentionDays: Number of days the logs are kept.
#   deletionDays: Number of days after which the logs are deleted.
#   topic: Apache Kafka topic name.
#   agentStatus: agent status message queue
#     offsetReset: offset for the message queue
#     topic: agent status message topic
#     group: agent status consumer group
#     partitions: agent status partitions
#     replicas: agent status replicas
#   agentScheduler: scheduler message queue
#     offsetReset: offset for the message queue
#     topic: scheduler message topic
#     group: scheduler consumer group
#     partitions: scheduler partitions
#     replicas: scheduler replicas
#   jobStatus: job status message queue
#     offsetReset: offset for the message queue
#     topic: job status message topic
#     group: job status consumer group
#     partitions: job status partitions
#     replicas: job status replicas
#   jobLogging: job logging message queue
#     offsetReset: offset for the message queue
#     topic: job logging message topic
#     group: job logging consumer group
#     partitions: job logging partitions
#     replicas: job logging replicas
#
kafka:
  bootstrapAddress: batch-kafka:9092
  maxRequestSize: 4194304
  retentionDays: 1
  deletionDays: 1
  active: true
  agentStatus:
    offsetReset: latest
    topic: batchAgentStatus
    group: batchlistener
    partitions: 5
    replicas: 1
  agentScheduler:
    offsetReset: latest
    topic: batchAgentScheduler
    group: batchlistener
    partitions: 5
    replicas: 1
  jobLogging:
    offsetReset: latest
    topic: batchJobExecutionLog
    partitions: 5
    replicas: 1
    level: DEBUG
  jobStatus:
    offsetReset: latest
    topic: batchJobStatus
    partitions: 5
    replicas: 1
