#
# MPM agent configuration file
#
# This configuration file is only used by the docker image.
#

spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
    web-application-type: none
  quartz:
    job-store-type: memory
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  kafka:
    listener:
      concurrency: 5

#
# Agent configuration:
#   library: sub system for the batch-job downloads
#     directory: directory where the batch-job JARs will be stored
#     server: download server for batch-job JARs
#     port: server port for the downloads
#   listener: job log, job execution status message listener
#     server: name of the listener host
#   scheduler: job scheduler host
#     server: name of the scheduler host
#   agent: agent configuration
#     hostName: hostname of the agent host
#     nodeName: node name for MBM agent
#     pingInterval: ping interval in ms.
#     performanceInterval: interval is ms for the performance collector.
#
mbm:
  library:
    jobs: ./jobs
    server: batch-manager
    port: 8090
    user: admin
    password: ENC(DtIzGPj615i3oxA5xbW+5G5Pf40SrKfCmRDe962SHB5lw9aBR+zdqiylP1Nzt329)
  listener:
    server: batch-listener
  scheduler:
    server: batch-scheduler
  agent:
    hostName: batch-agent-01
    nodeName: batch-agent-01
    pingInterval: 300000
    performanceInterval: 60000
    docker:
      network: docker_default
      hostname: batch-agent-01


# Kafka configuration.
# bootstrapAddress: Kafka server URL.
# maxRequestSize: Maximal request size (default: 4MB).
# retentionDays: Number of days the logs are kept.
# deletionDays: Number of days after which the logs are deleted.
# topic: Apache Kafka topic name.
kafka:
  bootstrapAddress: batch-kafka:9092
  maxRequestSize: 4194304
  retentionDays: 1
  deletionDays: 1
  active: true
  jobLogging:
    offsetReset: latest
    topic: batchJobExecutionLog
    partitions: 5
    replicas: 1
    level: DEBUG
  jobStatus:
    offsetReset: latest
    topic: batchJobStatus
    partitions: 5
    replicas: 1
  agentStatus:
    offsetReset: latest
    topic: batchAgentStatus
    group: batchmanager
    partitions: 5
    replicas: 1
  agentScheduler:
    offsetReset: latest
    topic: batchAgentScheduler
    group: batchmanager
    partitions: 5
    replicas: 1
