#
# MBM performance collector batch job configuration
#

# Spring configurations
spring:
  main:
    banner-mode: off
    web-application-type: none
  datasource:
    url: jdbc:mysql://batch-db:3306/batch
    username: admin
    password: ENC(DtIzGPj615i3oxA5xbW+5G5Pf40SrKfCmRDe962SHB5lw9aBR+zdqiylP1Nzt329)
    driverClassName: com.mysql.cj.jdbc.Driver
  batch:
    initialize-schema: never

# Batch Kafka configuration
# bootstrapAddress: Kafka server URL
# maxRequestSize: Maximal request size (default: 4MB)
kafka:
  bootstrapAddress: batchmanager:9092
  maxRequestSize: 4194304
  retentionDays: 1
  deletionDays: 1
  active: true
  jobStatus:
    offsetReset: latest
    topic: batchJobStatus
    partitions: 5
    replicas: 1
  jobLogging:
    offsetReset: latest
    topic: batchJobExecutionLog
    partitions: 5
    replicas: 1
    level: DEBUG

