# General spring configurations
spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
    web-application-type: none
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  batch:
    initialize-schema: never

# MySQL database
mysql:
  datasource:
    jdbc-url: jdbc:mysql://batchmanager:3306/batch
    username: root
    password: Dilbert_01
    driverClassName: com.mysql.cj.jdbc.Driver

# Batch Kafka configuration
# bootstrapAddress: Kafka server URL
# maxRequestSize: Maximal request size (default: 4MB)
kafka:
  bootstrapAddress: batchmanager:9092
  maxRequestSize: 4194304
  retentionDays: 1
  deletionDays: 1
  active: true
  jobStatus:
    offsetReset: latest
    topic: batchJobStatus
    partitions: 1
    replicas: 1
  jobLogging:
    offsetReset: latest
    topic: batchJobExecutionLog
    partitions: 1
    replicas: 1
    level: DEBUG

