drop table IF EXISTS DOCUMENTATION_LIFECYCLE;

create TABLE DOCUMENTATION_LIFECYCLE
(
    ID                    VARCHAR(36) NOT NULL PRIMARY KEY,
    RELATIVE_NUMBER       INTEGER     NOT NULL,
    CHANGED_BY_MC_N       VARCHAR(6), -- to be deleted when synchronization is not needed anymore
    CHANGED_BY_MC_S       SMALLINT,   -- to be deleted when synchronization is not needed anymore
    CHANGED_BY            VARCHAR(8)  NOT NULL,
    CHANGED_LOCATION      VARCHAR(1)  NOT NULL DEFAULT 'H',
    LAST_CHANGE           BIGINT      NOT NULL,
    IMPORT_EXPORT_FLAG    ENUM ('E', 'I', 'B'),
    STATUS_DOC_TYPE       ENUM ('SI', 'AN', 'MD', 'HB', 'DO', 'SN'),
    PHASE                 ENUM ('O', 'C', 'D', 'R'),
    DIRECTION             ENUM ('I', 'O', 'N', 'X'),
    MEDIUM                ENUM ('A', 'F', 'E', 'M', 'W', 'O', 'T', 'I', 'P'),
    ACTION_QUALIFIER      ENUM ('C', 'D', 'F', 'I', 'M', 'P', 'R', 'S', 'AP', 'AR', 'AS', 'CO', 'CR', 'CS', 'CT', 'DR', 'DS', 'DW', 'ED', 'EP', 'ER', 'GR', 'GS', 'HR', 'HS', 'LF', 'LR', 'ML', 'MR', 'NC', 'NO', 'OR', 'OS', 'PA', 'PR', 'RD', 'RR', 'RS', 'RL', 'RM', 'RU', 'UI', 'UP', 'VC', 'VR', 'WA', 'WF'),
    STATUS_PARTY_FUNCTION ENUM ('CU', 'FF'),
    STATUS_PARTY_MC_N     VARCHAR(6), -- to be deleted when synchronization is not needed anymore
    STATUS_PARTY_MC_S     SMALLINT,   -- to be deleted when synchronization is not needed anymore
    NUMERIC_QUALIFIER     INTEGER,
    DATETIME_OF_EVENT     DATETIME,
    STATUS_DESCRIPTION    VARCHAR(50),
    MESSAGE               VARCHAR(10),
    CONTAINER             VARCHAR(13),
    REMARK                VARCHAR(79),
    RECEIVED_DOC_ID       VARCHAR(40),
    PAGE_FROM             SMALLINT,
    PAGE_TO               SMALLINT,
    CORRECTION_REAS_01    VARCHAR(3),
    CORRECTION_REAS_02    VARCHAR(3),
    CORRECTION_REAS_03    VARCHAR(3),
    CORRECTION_REAS_04           VARCHAR(3),
    CORRECTION_REAS_05           VARCHAR(3),

    PLANNED_SHIPMENT_ID          VARCHAR(36),
    DOCUMENTATION_REQUEST_ID     VARCHAR(36),
    DOCUMENTATION_INSTRUCTION_ID VARCHAR(36),
    STATUS_PARTY_ID              VARCHAR(36),
    CHANGED_BY_ID                VARCHAR(36),
    CONSTRAINT FK_DOCUMENTATION_LIFECYCLE_PLANNED_SHIPMENT FOREIGN KEY (PLANNED_SHIPMENT_ID)
        REFERENCES PLANNED_SHIPMENT (ID),
    CONSTRAINT FK_DOCUMENTATION_LIFECYCLE_DOCUMENTATION_REQUEST FOREIGN KEY (DOCUMENTATION_REQUEST_ID)
        REFERENCES DOCUMENTATION_REQUEST (ID),
    CONSTRAINT FK_DOCUMENTATION_LIFECYCLE_DOCUMENTATION_INSTRUCTION FOREIGN KEY (DOCUMENTATION_INSTRUCTION_ID)
        REFERENCES DOCUMENTATION_INSTRUCTION (ID),
    CONSTRAINT FK_DOCUMENTATION_LIFECYCLE_STATUS_PARTY_FUNCTION FOREIGN KEY (STATUS_PARTY_ID)
        REFERENCES ORGANIZATION_PLACE (ID),
    CONSTRAINT FK_DOCUMENTATION_LIFECYCLE_CHANGED_BY_FUNCTION FOREIGN KEY (CHANGED_BY_ID)
        REFERENCES ORGANIZATION_PLACE (ID)
);

create UNIQUE INDEX IDX_DOCUMENTATION_LIFECYCLE_1 ON DOCUMENTATION_LIFECYCLE (PLANNED_SHIPMENT_ID ASC,
                                                                              DOCUMENTATION_REQUEST_ID ASC,
                                                                              RELATIVE_NUMBER ASC);

create INDEX IDX_DOCUMENTATION_LIFECYCLE_2 ON DOCUMENTATION_LIFECYCLE (PLANNED_SHIPMENT_ID ASC, DOCUMENTATION_REQUEST_ID
                                                                       ASC, RELATIVE_NUMBER ASC, LAST_CHANGE ASC);
