DROP VIEW IF EXISTS documentation_request_view;

CREATE VIEW documentation_request_view AS
	SELECT
	d.ID AS ID,
	p1.NUMBER AS NUMBER,
	p1.CLIENT AS CLIENT,
	d.RELATIVE_NUMBER AS RELATIVE_NUMBER,
    d.NOTICES_ID,
    d.STATUS,
    d.PRIORITY,
    l1.BUSINESS_LOCODE AS START_LOCODE,
    l2.BUSINESS_LOCODE AS END_LOCODE,
    o1.MATCHCODE_NAME AS CUSTOMER_MATCHCODE_NAME,
    o1.MATCHCODE_SUPPLEMENT AS CUSTOMER_MATCHCODE_SUPPLEMENT,
    o2.MATCHCODE_NAME AS ISSUER_MATCHCODE_NAME,
    o2.MATCHCODE_SUPPLEMENT AS ISSUER_MATCHCODE_SUPPLEMENT
FROM DOCUMENTATION_REQUEST d
LEFT JOIN LOCATION l1 ON d.start_location = l1.ID
LEFT JOIN LOCATION l2 ON d.end_location = l2.ID
LEFT JOIN ORGANIZATION_PLACE o1 ON d.CUSTOMER_ID = o1.ID
LEFT JOIN ORGANIZATION_PLACE o2 ON d.ISSUER_ID = o2.ID
LEFT JOIN PLANNED_SHIPMENT p1 ON d.PLANNED_SHIPMENT_ID = p1.ID;