DROP TABLE IF EXISTS GEO_HIERARCHY;

-- Old DB2 table: TS1530
CREATE TABLE GEO_HIERARCHY
(
    ID                  VARCHAR(36) NOT NULL PRIMARY KEY,
    CLIENT              VARCHAR(1)  NOT NULL,
    GEO_REGION_ID       VARCHAR(1)  NOT NULL,
    GEO_SUBREGION_ID    VARCHAR(2),
    GEO_AREA_ID         VARCHAR(2),
    GEO_SUBAREA_ID      VARCHAR(3),
    GEO_DISTRICT_ID     VARCHAR(1),
    GEO_HIER_ID_STRING  VARCHAR(9),
    NAME                VARCHAR(20) NOT NULL,
    SHORT_NAME          VARCHAR(9)  NOT NULL,
    HIER_LEVEL_CODE     VARCHAR(2)  NOT NULL,
    HIER_LEVEL_NAME     VARCHAR(18) NOT NULL,
    HIER_LEVEL_POSITION SMALLINT    NOT NULL,
    VALID_FROM          DATE,
    VALID_TO            DATE,
    LC_VALID_STATE_A    ENUM ('A', 'D', 'H', 'P'),
    LAST_CHANGE         BIGINT      NOT NULL,
    CHANGED_BY          VARCHAR(8),
    CHANGE_LOCATION     VARCHAR(1),
    FK_TS1540CLIENT     VARCHAR(1),
    FK_TS1540SALES_REG  VARCHAR(1),
    FK_TS1540SUBREGION  VARCHAR(2),
    FK_TS1540SALES_ARE  VARCHAR(2),
    FK_TS1540SALES_OFF  VARCHAR(3),
    FK_TS1540SALES_TEA  VARCHAR(2),
    FK_TS1990CLIENT     VARCHAR(1),
    FK_TS1990SALES_REG  VARCHAR(1),
    FK_TS1990SALES_SUB  VARCHAR(2),
    FK_TS1990SALES_ARE  VARCHAR(2),
    FK_TS1990SALES_OFF  VARCHAR(3),
    FK_TS1990SALES_TEA  VARCHAR(2),
    FK0TS0120CLIENT     VARCHAR(1),
    FK0TS0120NUMBER     INTEGER
);

CREATE UNIQUE INDEX IDX_GEO_HIERARCHY_1 ON GEO_HIERARCHY (CLIENT ASC, GEO_REGION_ID ASC, GEO_SUBREGION_ID ASC,
                                                          GEO_AREA_ID ASC, GEO_SUBAREA_ID ASC, GEO_DISTRICT_ID ASC);

CREATE INDEX IDX_GEO_HIERARCHY_2 ON GEO_HIERARCHY (CLIENT ASC, GEO_REGION_ID ASC, GEO_SUBREGION_ID ASC, GEO_AREA_ID ASC,
                                                   GEO_SUBAREA_ID ASC, GEO_DISTRICT_ID ASC, LAST_CHANGE ASC);
