DROP TABLE IF EXISTS SECURITY_ORGANIZATION;

-- Old DB2 table: TZ0110
CREATE TABLE SECURITY_ORGANIZATION
(
    ID                   VARCHAR(36) NOT NULL PRIMARY KEY,
    IDENTIFIER           VARCHAR(10) NOT NULL,
    CLIENT               VARCHAR(1)  NOT NULL,
    HISTORY_FROM         BIGINT      NOT NULL,
    ORG_NUMBER           INTEGER,
    MATCHCODE            VARCHAR(6),
    MATCHCODE_EXTENSION  SMALLINT,
    SHORT_NAME           VARCHAR(25),
    LOCATION             VARCHAR(25),
    ORG_UNIT_FRT_BIZ     VARCHAR(8),
    THIRD_P_ORG_PL_NUM   INTEGER,
    DISPO_AREA_START     VARCHAR(10),
    DISPO_AREA_END       VARCHAR(10),
    DISPO_AREA_EQUIPMENT VARCHAR(10),
    TRUSTWORTH_CLASS     VARCHAR(1),
    CHANGED_BY           VARCHAR(8),
    LAST_CHANGE          BIGINT      NOT NULL,
    CHANGE_LOCATION      VARCHAR(1)
);

CREATE UNIQUE INDEX IDX_SECURITY_ORGANIZATION_1 ON SECURITY_ORGANIZATION (CLIENT ASC, IDENTIFIER ASC, HISTORY_FROM ASC);

CREATE UNIQUE INDEX IDX_SECURITY_ORGANIZATION_2 ON SECURITY_ORGANIZATION (CLIENT ASC, ORG_NUMBER ASC, IDENTIFIER ASC, HISTORY_FROM ASC);

CREATE INDEX IDX_SECURITY_ORGANIZATION_3 ON SECURITY_ORGANIZATION (CLIENT ASC, MATCHCODE ASC, MATCHCODE_EXTENSION ASC, HISTORY_FROM ASC);

CREATE INDEX IDX_SECURITY_ORGANIZATION_4 ON SECURITY_ORGANIZATION (CLIENT ASC, IDENTIFIER ASC, HISTORY_FROM ASC);

