DROP TABLE IF EXISTS USERS;

-- Old DB2 table: TZ0120
CREATE TABLE USERS
(
    ID                 VARCHAR(36) NOT NULL PRIMARY KEY,
    USER_ID            VARCHAR(8)  NOT NULL,
    HISTORY_FROM       BIGINT,
    AUTOKEY_YES_NO     BIT,
    AUTOSAVE_YES_NO    BIT,
    CHANGED_BY         VARCHAR(8),
    LAST_CHANGE        BIGINT,
    CHANGE_LOC         VARCHAR(1),
    PNO                SMALLINT,
    CLIENT             VARCHAR(1)  NOT NULL,
    NAME               VARCHAR(30) NOT NULL,
    PHONE              VARCHAR(20),
    MEMO_DESTINATION   VARCHAR(17),
    FAKSIMILE          VARCHAR(20),
    DATA_FROM_RACF     BIT,
    LOCATION           VARCHAR(8),
    LOCAL_PRINTER      VARCHAR(8),
    UTC_DIFF           SMALLINT,
    LOCATION_NO        INTEGER,
    LANGUAGE_CODE      VARCHAR(2),
    LAST_LOGON_HH      DATE,
    LAST_LOGON_NY      DATE,
    LAST_LOGON_SI      DATE,
    NEXT_FULL_LOGON_HH DATE,
    NEXT_FULL_LOGON_NY DATE,
    NEXT_FULL_LOGON_SI DATE,
    MAILADDRESS        VARCHAR(100),
    IMPERIAL_METRIC    VARCHAR(1),
    LAST_LOGON         BIGINT,
    VERSION            INT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IDX_USERS_1 ON USERS (USER_ID ASC, HISTORY_FROM ASC);

CREATE INDEX IDX_USERS_2 ON USERS (USER_ID ASC, HISTORY_FROM ASC, LAST_CHANGE ASC);

