DROP TABLE IF EXISTS CLIENT_AUTHORIZATION;

-- Old DB2 table: TZ1060
CREATE TABLE CLIENT_AUTHORIZATION
(
    ID                   VARCHAR(36) NOT NULL PRIMARY KEY,
    ID_CODE              VARCHAR(1),
    HISTORY_FROM         BIGINT,
    CHANGED_BY           VARCHAR(8),
    LAST_CHANGE          BIGINT,
    CHANGE_LOC           VARCHAR(1) DEFAULT 'H',
    THIRD_P_ORG_PL       INTEGER,
    SECU_ORGANIZATION_ID VARCHAR(36),
    USERS_ID             VARCHAR(36),
    CONSTRAINT FK_CLIENT_AUTHORIZATION_SECURITY_ORGANIZATION FOREIGN KEY (SECU_ORGANIZATION_ID)
        REFERENCES SECURITY_ORGANIZATION (ID),
    CONSTRAINT FK_CLIENT_AUTHORIZATION_USERS FOREIGN KEY (USERS_ID)
        REFERENCES USERS (ID)
);

CREATE UNIQUE INDEX IDX_CLIENT_AUTHORIZATION_1 ON CLIENT_AUTHORIZATION (SECU_ORGANIZATION_ID ASC, USERS_ID ASC, HISTORY_FROM ASC, ID_CODE ASC);

CREATE INDEX IDX_CLIENT_AUTHORIZATION_3 ON CLIENT_AUTHORIZATION (ID_CODE ASC, USERS_ID ASC, HISTORY_FROM ASC);

CREATE INDEX IDX_CLIENT_AUTHORIZATION_4 ON CLIENT_AUTHORIZATION (ID_CODE ASC);