DROP TABLE IF EXISTS LOCATION;

-- Old Db2 table: TS0120
CREATE TABLE LOCATION
(
    ID                   VARCHAR(36) NOT NULL PRIMARY KEY,
    NUMBER               INT         NOT NULL,
    CLIENT               VARCHAR(1)  NOT NULL,
    LAST_CHANGE          BIGINT        NOT NULL,
    CHANGE_LOCATION      VARCHAR(1),
    CHANGED_BY           VARCHAR(8),
    LC_VALID_STATE_R     ENUM('D', 'R'),
    VALID_FROM           DATE,
    VALID_TO             DATE,
    CL_TYPE              VARCHAR(3),
    CL_SOURCE            ENUM('E', 'I'),
    PORT_TYPE            ENUM('N', 'S'),
    CUSTOMS_FREE_ZONE    BIT,
    BUSINESS_LOCATION        VARCHAR(35),
    BUSINESS_LOCODE          VARCHAR(5),
    BUSINESS_POSTAL_CODE     VARCHAR(9),
    CONTINENT_ABBREVIATION   VARCHAR(2),
    COUNTRY_ABBREVIATION     VARCHAR(2),
    REGION_CODE              VARCHAR(3),
    GEOGRAPHICAL_UNIT        VARCHAR(9),
    STANDARD                 BIT,
    CONNECTION_MARITIME      BIT,
    CONNECTION_RAIL          BIT,
    CONNECTION_ROAD          BIT,
    CONNECTION_AIR           BIT,
    UN_FLAG              VARCHAR(1),
    PRINT_LOC_NAME       VARCHAR(35),
    SCHEDULE_D_K_CD      VARCHAR(10),
    CA_CUSTOMS_CODE      VARCHAR(10),
    SHOW_IN_INTERNET     VARCHAR(1),
    COORDINATE_LONGITUDE DECIMAL(9,6),
    COORDINATE_LATITUDE  DECIMAL(8,6),
    COORDINATE_SOURCE    VARCHAR(2),
    CONNECTING_HUB       BIT,
    CHANGE_SOURCE_VALUE  VARCHAR(5),
    CHANGE_TARGET_VALUE  VARCHAR(5),
    CHANGE_ACTION        VARCHAR(2),
    CHANGE_STATUS        VARCHAR(1),
    GEO_HIERARCHY_ID     VARCHAR(36),
    CONSTRAINT FK_LOCATION_GEO_HIERARCHY FOREIGN KEY (GEO_HIERARCHY_ID) REFERENCES GEO_HIERARCHY (ID)

--   FK_TS0210CLIENT      VARCHAR(1),
--   FK_TS0210NUMBER      INT,
--   FK_TS0120CLIENT      VARCHAR(1),
--   FK_TS0120NUMBER      INT,
--   FK_TS1530GEO_DESTR   VARCHAR(1),
--   FK_TS1530GEO_SUBAR   VARCHAR(3),
--   FK_TS1530GEO_AREA    VARCHAR(2),
--   FK_TS1530GEO_SUBRE   VARCHAR(2),
--   FK_TS1530GEO_REGIO   VARCHAR(1),
--   FK_TS1530CLIENT      VARCHAR(1),
--   FK_TS1320CLIENT      VARCHAR(1),
--   FK_TS1320ID_NUMBER   INT,
);

CREATE UNIQUE INDEX IDX_LOCATION_1 ON LOCATION (CLIENT ASC, NUMBER ASC);

CREATE INDEX IDX_LOCATION_2 ON LOCATION (CLIENT ASC, NUMBER ASC, LAST_CHANGE ASC);

CREATE INDEX IDX_LOCATION_3 ON LOCATION (CLIENT ASC, BUSINESS_LOCODE ASC);

