DROP TABLE IF EXISTS CLIENT;

-- Old DB2 table: TZ0019
CREATE TABLE CLIENT
(
    ID          VARCHAR(36) NOT NULL PRIMARY KEY,
    ID_CODE     VARCHAR(1)  NOT NULL,
    NAME        VARCHAR(32) NOT NULL,
    SHORT_NAME  VARCHAR(3)  NOT NULL,
    VERSION     INT         NOT NULL DEFAULT 0,
    LAST_CHANGE BIGINT      NOT NULL,
    CHANGE_LOC  VARCHAR(1),
    CHANGED_BY  VARCHAR(8)
);

CREATE UNIQUE INDEX IDX_CLIENT_1 ON CLIENT (ID_CODE);

