DROP TABLE IF EXISTS USER_BASIS;

CREATE TABLE USER_BASIS
(
    ID              VARCHAR(36) NOT NULL PRIMARY KEY,
    SURNAME         VARCHAR(30) NOT NULL,
    FIRSTNAME       VARCHAR(20) NOT NULL,
    EMPLOYEE_TYPE   VARCHAR(5),
    SEX             ENUM('F', 'M'),
    LANGUAGE_CODE   VARCHAR(2),
    FORM_OF_ADDRESS VARCHAR(8),
    PART_TIME       VARCHAR(1),
    EMPLOYED_FROM   DATE,
    EMPLOYED_UNTIL  DATE,
    LAST_CHANGE     BIGINT,
    CHANGED_BY      VARCHAR(8)  NOT NULL,
    USERS_ID        VARCHAR(36),
    CONSTRAINT FK_USER_BASIS_USERS FOREIGN KEY (USERS_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_USER_BASIS_1 ON USER_BASIS (SURNAME ASC,FIRSTNAME ASC);
CREATE INDEX IDX_USER_BASIS_2 ON USER_BASIS (SURNAME ASC,FIRSTNAME ASC, LAST_CHANGE ASC);
