DROP TABLE IF EXISTS CLIENT_ROLE_OWNERSHIP;

-- Old DB2 table: TZ1900
CREATE TABLE CLIENT_ROLE_OWNERSHIP
(
    ID              VARCHAR(36) NOT NULL PRIMARY KEY,
    CLIENT          VARCHAR(1)  NOT NULL,
    RELATIVE_NUMBER SMALLINT    NOT NULL,
    OWNER_ID        VARCHAR(8),
    DESCRIPTION     VARCHAR(254),
    VALID_FROM      DATE,
    CHANGED_BY      VARCHAR(8)  NOT NULL,
    CHANGE_LOCATION VARCHAR(1),
    LAST_CHANGE     LONG        NOT NULL,
    USER_ROLE_ID    VARCHAR(36),
    CONSTRAINT FK_CLIENT_ROLE_OWNERSHIP_USER_ROLE FOREIGN KEY (USER_ROLE_ID)
        REFERENCES USER_ROLE (ID)
);

CREATE UNIQUE INDEX IDX_CLIENT_ROLE_OWNERSHIP_1 ON CLIENT_ROLE_OWNERSHIP (CLIENT ASC, RELATIVE_NUMBER ASC, USER_ROLE_ID ASC);

