DROP TABLE IF EXISTS USER_ROLE;

-- Old DB2 table: TZ1820
CREATE TABLE USER_ROLE
(
    ID                 VARCHAR(36) NOT NULL PRIMARY KEY,
    ENVIRONMENT        VARCHAR(1)  NOT NULL,
    IDENTIFIER         SMALLINT    NOT NULL,
    NAME               VARCHAR(32) NOT NULL,
    SHORT_DESCRIPTION  VARCHAR(60),
    CLASSIFIER         VARCHAR(1),
    LAST_CHANGE        LONG        NOT NULL,
    CHANGED_BY         VARCHAR(8)  NOT NULL,
    CHANGE_LOCATION    VARCHAR(1),
    DE_THD_IDENTIFIER  INT,
    RELEASED_ON        DATE,
    HIGH_SECURITY_FLAG BIT
);

CREATE UNIQUE INDEX IDX_USER_ROLE_1 ON USER_ROLE(ENVIRONMENT ASC, IDENTIFIER ASC);

CREATE INDEX IDX_USER_ROLE_2 ON USER_ROLE(ENVIRONMENT ASC, IDENTIFIER ASC);
