DROP TABLE IF EXISTS DOCUMENTATION_INSTRUCTION;

CREATE TABLE DOCUMENTATION_INSTRUCTION
(
    ID              VARCHAR(36) NOT NULL PRIMARY KEY,
    RELATIVE_NUMBER SMALLINT    NOT NULL,
    CHANGED_BY      VARCHAR(8)  NOT NULL,
    CHANGE_LOC      VARCHAR(1)           DEFAULT 'H',
    LAST_CHANGE     BIGINT,
    DOCUMENT_NO     VARCHAR(17) NOT NULL DEFAULT '',
    DOCUMENT_TYPE   ENUM ('AN', 'DO', 'HB', 'MD'),
    MTD_NO_SUFFIX   ENUM ('A', 'AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI', 'AJ', 'AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AV', 'AW', 'AX', 'AY', 'AZ', 'B', 'BA', 'BB', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BK', 'BL', 'BM', 'BN', 'BO', 'BP', 'BQ', 'BR', 'BS', 'BT', 'BU', 'BV', 'BW', 'BX', 'BY', 'BZ', 'C', 'CA', 'CB', 'CC', 'CD', 'CE', 'CF', 'CG', 'CH', 'CI', 'CJ', 'CK', 'CL', 'CM', 'CN', 'CO', 'CP', 'CQ', 'CR', 'CS', 'CT', 'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'D', 'DA', 'DB', 'DC', 'DD', 'DE', 'DF', 'DG', 'DH', 'DI', 'DJ', 'DK', 'DL', 'DM', 'DN', 'DO', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'),
    DOC_STATUS               ENUM ('C', 'I'),
    DOC_NO_FIXED             BIT(1),
    DOC_PRINTED              BIT(1),
    TO_BE_DOCUMENTED         BIT(1),
    PLACE_OF_ISSUE           VARCHAR(17),
    DATE_OF_ISSUE            DATE,
    DATE_OF_CREATION         DATE,
    DATE_OF_ISSUE_ORIG       ENUM ('D', 'F', 'P'),
    CONDENSED                BIT(1),
    FREIGHTED                BIT(1),
    CURR_FOR_TOTAL           VARCHAR(3),
    NO_OF_COPIES             INTEGER,
    NO_OF_ORIGINALS          INTEGER,
    COPIES_UNFREIGHTED       INTEGER,
    ORIGS_UNFREIGHTED        INTEGER,
    PRINT_CARGO_VALUE        BIT(1),
    PAYABLE_AT               VARCHAR(17),
    INCOTERMS                VARCHAR(3),
    DP_VOYAGE_NO_1           INTEGER,
    SCHEDULE_VOY_NO_1        VARCHAR(10),
    VESSEL_NAME_1            VARCHAR(35),
    DP_VOYAGE_NO_2           INTEGER,
    SCHEDULE_VOY_NO_2        VARCHAR(10),
    VESSEL_NAME_2            VARCHAR(35),
    MD_TYPE                  ENUM ('BL', 'EE', 'EF', 'ES', 'EV', 'EX', 'OE', 'OV', 'SW'),
    MD_OP_CU_TYPE            ENUM ('BO', 'OP'),
    MD_PRE_ALLOCATED         BIT(1),
    MD_ISSUE_ELSEWHERE       BIT(1),
    MD_ORDER_BL              BIT(1),
    MD_ROE_DATE              DATE,
    MD_ROE_ORIGIN            ENUM ('ASI', 'ECB', 'EU1', 'GEN', 'IRR'),
    MD_ROE_PREP_COLL         ENUM ('A', 'C', 'P'),
    MD_REC_FOR_SHIPMT        BIT(1),
    MD_REC_FOR_SH_DATE       DATE,
    MDC_DATE_SHIPPED         DATE,
    MDC_DATE_SHIP_ORIG       VARCHAR(1),
    MDC_SHIPPED_ON_BRD       BIT(1),
    TO_ORDER_TEXT            VARCHAR(29),
    LANGUAGE0                VARCHAR(2),
    PRINT_UNIT_TEMP          ENUM ('C', 'F'),
    PRINT_UNIT_WEIGHT        ENUM ('PCT', 'KG', 'KGM', 'KGS', 'LB', 'LBR', 'LBS', 'STN', 'TNE'),
    ADDTL_UNIT_OF_WT         ENUM ('PCT', 'KG', 'KGM', 'KGS', 'LB', 'LBR', 'LBS', 'STN', 'TNE'),
    PRINT_DG_INFO            BIT(1),
    DATE_FORMAT              SMALLINT,
    DATE_SEPARATOR           VARCHAR(1),
    DECIMAL_SEPARATOR        VARCHAR(1),
    STARTING_PAGE            SMALLINT,
    UNIT_OF_VOLUME           ENUM ('BLL', 'CBM', 'CFT', 'FTQ', 'GLI', 'LTR', 'MTQ', 'M3'),
    ADDTL_UNIT_OF_VOL        ENUM ('BLL', 'CBM', 'CFT', 'FTQ', 'GLI', 'LTR', 'MTQ', 'M3'),
    NO_OF_DECIMALS_VOL       SMALLINT,
    NO_OF_DECIMALS_WT        SMALLINT,
    TOTAL_FOR_VOL_PRNT       BIT(1),
    TOTAL_FOR_WT_PRINT       BIT(1),
    TOTAL_FOR_PACK_PRT       BIT(1),
    APP_OF_NO_OF_ORIG        ENUM ('N', 'T'),
    CY_CFS_PRINT_PLA         ENUM ('B', 'F', 'N'),
    CY_CFS_PRINT_PLD         ENUM ('B', 'F', 'N'),
    CY_CFS_TEXT_PLA          VARCHAR(15),
    CY_CFS_TEXT_PLD          VARCHAR(15),
    ROE_PRINT                BIT(1),
    FAC_PRINT                BIT(1),
    APP_OF_CHARGES_FRE       ENUM ('B', 'BI', 'C', 'CI', 'N', 'P','PI'),
    APP_OF_CHARGES_UNF       ENUM ('B', 'BI', 'C', 'CI', 'N', 'P','PI'),
    ORDER_OF_FREIGHTS        ENUM ('A', 'B', 'C'),
    PLACE_OF_FREIGHTS        ENUM ('A', 'B', 'C'),
    CARRIER_CLAUSE_1         VARCHAR(35),
    CARRIER_CLAUSE_2         VARCHAR(35),
    CARRIER_CLAUSE_3         VARCHAR(35),
    ATTACH_LIST_CLAUSE       VARCHAR(30),
    ATT_L_CLAUSE_PRINT       BIT(1),
    ATTACH_LIST_PRINT        ENUM ('N', 'P', 'T'),
    PAY_TO_CLAUSE_PRNT       BIT(1),
    PRINT_CONTACT            ENUM ('E', 'I', 'N', 'Y'),
    PRINT_HS_CODE            BIT(1),
    LAYOUT_VARIANTE          VARCHAR(1),
    COPY_FOR_TPF_1           ENUM ('CC', 'CN', 'FF', 'IF', 'IS', 'NX', 'N1', 'N2', 'PC', 'SH'),
    COPY_FOR_TPF_2           ENUM ('CC', 'CN', 'FF', 'IF', 'IS', 'NX', 'N1', 'N2', 'PC', 'SH'),
    COPY_FOR_TPF_3           ENUM ('CC', 'CN', 'FF', 'IF', 'IS', 'NX', 'N1', 'N2', 'PC', 'SH'),
    COPY_FOR_TPF_4           ENUM ('CC', 'CN', 'FF', 'IF', 'IS', 'NX', 'N1', 'N2', 'PC', 'SH'),
    PRINT_ARTICLE_NO         BIT(1),
    PRINT_DATE_O_ISSUE       BIT(1),
    C_ITEM_CHARGE_PRNT       BIT(1),
    DOC_CHARGE_PRINT         BIT(1),
    PRINT_FREIGHT_REF        BIT(1),
    OVERDIMENSIONS           BIT(1),
    PRINT_NET_WEIGHT         BIT(1),
    PLACE_ADDTL_NOTIFY       VARCHAR(1),
    PRINT_SC_NUMBER          BIT(1),
    SUP_REVENUE_TOTALS       BIT(1),
    GRP_CONTAINER_INFO       BIT(1),
    PRINT_PLA_ADDRESS        BIT(1),
    PRINT_PLD_ADDRESS        BIT(1),
    DRAFT_REQUIRED           BIT(1),
    FORM_USAGE               BIT(1),
    DATE_OF_COLLECTION       DATE,
    USER_OF_COLLECTION       VARCHAR(8),
    DATE_IMP_PAYMT_REC       DATE,
    USER_IMP_PAYMT_REC       VARCHAR(8),
    IMPORT_PAYMENT_REC       ENUM ('Y','N','V'),
    DATETIME_DOCUM_ARRIVAL   DATETIME,
    MSG_CODE                 VARCHAR(8),
    PRINTER_ID               VARCHAR(8),
    CU_PRT_ORIG_FRTD         SMALLINT,
    CU_PRT_ORIG_UNFRTD       SMALLINT,
    CU_PRT_COPY_FRTD         SMALLINT,
    CU_PRT_COPY_UNFRTD       SMALLINT,
    DISTR_FULL_SET           BIT(1),
    RELEASE_APPROVED         BIT(1),
    DATE_REL_APPROVED        DATE,
    RELEASE_INFO_ID          INTEGER,
    COLLECT_INFO_ID          INTEGER,
    PRINTOUT_LIST            INTEGER,
    PRINTOUT_PAGE_FROM       INTEGER,
    PRINTOUT_PAGE_TO         INTEGER,
    USER_REL_APPROVED        VARCHAR(8),
    CONTACT_USER_ID          VARCHAR(8),
    CONTACT_REF_NAME         VARCHAR(35),
    PRINT_ADD_CUS_DTLS       BIT(1),
    PRINT_MT_RET_DATE        BIT(1),
    PRINT_SOB_INFO           BIT(1),
    PRINT_VESSEL_FLAG        BIT(1),
    PRT_VSL_CALL_SIGN        BIT(1),
    PRINT_LLYODS_NO          BIT(1),
    PRINT_COMPUTED_VOL       BIT(1),

    SH_NUMBER_PRINT          ENUM ('A', 'B'),
    EXPORT_PAYMENT_REC       ENUM ('Y', 'N', 'R'),
    DOCUMENT_RELEASED        ENUM ('Y', 'N', 'R'),
    PRINT_ARRIVAL_TERM       ENUM ('L', 'N', 'S'),
    PRINT_CONT_TARE_WT       ENUM ('A', 'B', 'C', 'E', 'N'),
    PRINT_CTR_SP_CARGO       ENUM ('B', 'D', 'N', 'O'),
    PRINT_CUST_CGO_AV        ENUM ('A', 'C', 'N', 'R'),
    PRINT_OFFICE_ADDR        ENUM ('Y', 'N', 'S'),
    PRINT_OPER_ROUTING       ENUM ('F', 'L', 'N', 'O'),
    PRINT_REDELIVERY         ENUM ('A', 'H', 'N', 'R', 'Y'),
    PRINT_T_SHIPM_PORT       ENUM ('A', 'C', 'N', 'O'),
    PRINT_VSL_PORT_NUM       ENUM ('C', 'I', 'N'),
    PRINT_CARGO_DESCR        ENUM ('C', 'D', 'S'),

    PLANNED_SHIPMENT_ID      VARCHAR(36),
    DOCUMENTATION_REQUEST_ID VARCHAR(36),
    CONSTRAINT FK_DOCUMENTATION_INSTRUCTION_PLANNED_SHIPMENT FOREIGN KEY (PLANNED_SHIPMENT_ID)
        REFERENCES PLANNED_SHIPMENT (ID),
    CONSTRAINT FK_DOCUMENTATION_INSTRUCTION_DOCUMENTATION_REQUEST FOREIGN KEY (DOCUMENTATION_REQUEST_ID)
        REFERENCES DOCUMENTATION_REQUEST (ID)

--    ADDRESSEE_PFT      VARCHAR(2), // no data found
--    TELEX_RELEASE          VARCHAR(1), // no data found
--    DATE_TELEX_RELEASE     DATE, // no data found
--    USER_TELEX_RELEASE     VARCHAR(8), // no data found
--    OVERALL_VALUE_AMOU       DECIMAL(10, 2), // last data from 2016
--    OVERALL_VALUE_CURR       VARCHAR(3), // last data from 2016
--      DA_REF_TO_MTD       VARCHAR(17),
--      DA_REF_FREIGHT_MTD  VARCHAR(17),
--      DA_BOOK_VESSEL_COM  VARCHAR(1),
--      DA_OP_DP_VOYAGE_NO  INTEGER,
--      DA_OP_POL           VARCHAR(5),
--      DA_OP_POD           VARCHAR(5),
--      DA_DEF_STATUS_DO    VARCHAR(1),
--      DA_TO_BE_DOC_VIA    VARCHAR(17),
--      DA_CENTRE_TXT_ID    INTEGER,
--      DA_FRT_DETAILS_ID   INTEGER,
--      DA_FRTS_CENTRE_ID   INTEGER,
--      DA_RELVT_FOR_ARCHV  VARCHAR(1),
--      FK_TS0340CLIENT     VARCHAR(1)         NOT NULL,
--      FK_TS0340NUMBER     INTEGER         NOT NULL,
--      TBD_CORRECTION_COD  VARCHAR(3),
--      TBD_VALID_DISP_COD  VARCHAR(3),
--      TBD_CUSTOMS_STATE   VARCHAR(3),
--      TBD_CUST_STATE_DAT  DATE,
--      TBD_INBOND_CODE     VARCHAR(3),
--      TBD_INBOND_NUMBER   VARCHAR(12),
--      TBD_REL_ISSUE_DATE  DATE,
--      TBD_DP_VOY_NO_PRE   INTEGER,
--      TBD_SCH_VOY_NO_PRE  VARCHAR(10),
--      TBD_PRE_CARR_VE_NA  VARCHAR(35),
--      TBD_DO_DEST_OF_TRA  VARCHAR(8),
--      TBD_DO_LOCAL_PORT   VARCHAR(10),
--      TBD_DO_STORAGE_PLA  VARCHAR(8),
--      TBD_SHIP_EXPORT_DE  VARCHAR(1),
--      TBD_SED_EXCEPT_COD  VARCHAR(2),
--      TBD_EXP_MANFST_FIN  DATE,
--      TBD_EXP_MANIFEST_S  SMALLINT,
--      TBD_IMP_MANFST_FIN  DATE,
--      TBD_IMP_MANIFEST_S  SMALLINT,
--      TBD_FIRST_PRINT_DA  DATE,
--      TBD_FIRST_PRT_MSG   VARCHAR(8),
--      TBD_MD_VOY_POL_COM  VARCHAR(1),
--      TBD_MD_VOY_POL_DAT  DATE,
--      TBD_MD_VOY_POL_TIM  TIME,
--      TBD_CANCELLED_FLAG  VARCHAR(1),
--      TBD_RESDAT          DATE
);

CREATE UNIQUE INDEX IDX_DOCUMENTATION_INSTRUCTION_1 ON DOCUMENTATION_INSTRUCTION (PLANNED_SHIPMENT_ID, RELATIVE_NUMBER ASC);

CREATE INDEX IDX_DOCUMENTATION_INSTRUCTION_2 ON DOCUMENTATION_INSTRUCTION (PLANNED_SHIPMENT_ID, RELATIVE_NUMBER ASC, LAST_CHANGE ASC);

--  CREATE INDEX DB2PROD.IS055093
--      ON DB2PROD.TS0550 (FK_TS0340CLIENT ASC, DA_FRTS_CENTRE_ID ASC);
--
--  CREATE INDEX DB2PROD.IS055092
--      ON DB2PROD.TS0550 (FK_TS0340CLIENT ASC, DA_FRT_DETAILS_ID ASC);
--
--  CREATE INDEX DB2PROD.IS055091
--      ON DB2PROD.TS0550 (FK_TS0340CLIENT ASC, DA_CENTRE_TXT_ID ASC);
--
--  CREATE UNIQUE INDEX DB2PROD.IS055005
--      ON DB2PROD.TS0550 (DA_REF_FREIGHT_MTD ASC, DOCUMENT_TYPE ASC, MTD_NO_SUFFIX ASC, FK_TS0340CLIENT ASC, FK_TS0340NUMBER ASC, RELATIVE_NUMBER ASC, DOCUMENT_NO ASC);
--
--  CREATE UNIQUE INDEX DB2PROD.IS055004
--      ON DB2PROD.TS0550 (DA_REF_TO_MTD ASC, FK_TS0340CLIENT ASC, FK_TS0340NUMBER ASC, RELATIVE_NUMBER ASC, DOCUMENT_NO ASC);
--
--  CREATE UNIQUE INDEX DB2PROD.IS055015
--      ON DB2PROD.TS0550 (FK_TS0340CLIENT ASC, EXPORT_PAYMENT_REC ASC, FK_TS0340NUMBER ASC, RELATIVE_NUMBER ASC);
--
--  CREATE UNIQUE INDEX DB2PROD.IS055014
--      ON DB2PROD.TS0550 (FK_TS0340CLIENT ASC, DA_OP_DP_VOYAGE_NO ASC, DOCUMENT_TYPE ASC, DOC_STATUS ASC, DA_TO_BE_DOC_VIA ASC, FK_TS0340NUMBER ASC, RELATIVE_NUMBER ASC);
--
--  CREATE INDEX DB2PROD.IS055003
--      ON DB2PROD.TS0550 (DOCUMENT_NO ASC, FK_TS0340CLIENT ASC, FK_TS0340NUMBER ASC, RELATIVE_NUMBER ASC);
--
--  CREATE UNIQUE INDEX DB2PROD.IS055002
--      ON DB2PROD.TS0550 (FK_TS0340CLIENT ASC, FK_TS0340NUMBER ASC, DOCUMENT_NO ASC, DOCUMENT_TYPE ASC, MTD_NO_SUFFIX ASC, DOC_STATUS ASC, DOC_PRINTED ASC, FREIGHTED ASC, CONDENSED ASC, MD_TYPE ASC, RELATIVE_NUMBER ASC);
--
--  CREATE UNIQUE INDEX DB2PROD.IS055013
--      ON DB2PROD.TS0550 (FK_TS0340CLIENT ASC, DA_OP_DP_VOYAGE_NO ASC, DOCUMENT_TYPE ASC, DA_TO_BE_DOC_VIA DESC, DOC_STATUS ASC, FK_TS0340NUMBER ASC, RELATIVE_NUMBER ASC);
--
--  CREATE UNIQUE INDEX DB2PROD.IS055001
--      ON DB2PROD.TS0550 (FK_TS0340CLIENT ASC, FK_TS0340NUMBER ASC, RELATIVE_NUMBER ASC);
--
--  CREATE UNIQUE INDEX DB2PROD.IS055012
--      ON DB2PROD.TS0550 (DOCUMENT_TYPE ASC, DOC_STATUS ASC, DA_RELVT_FOR_ARCHV ASC, FK_TS0340CLIENT ASC, FK_TS0340NUMBER ASC, RELATIVE_NUMBER ASC, DOCUMENT_NO ASC);
--
--  CREATE INDEX DB2PROD.IS055011
--      ON DB2PROD.TS0550 (DOCUMENT_TYPE ASC, DA_TO_BE_DOC_VIA ASC, FK_TS0340CLIENT ASC, FK_TS0340NUMBER ASC);
--
--  CREATE UNIQUE INDEX DB2PROD.IS055010
--      ON DB2PROD.TS0550 (DA_OP_DP_VOYAGE_NO ASC, DOCUMENT_TYPE ASC, DA_OP_POD ASC, FK_TS0340CLIENT ASC, FK_TS0340NUMBER ASC, RELATIVE_NUMBER ASC);
--
--  CREATE UNIQUE INDEX DB2PROD.IS055009
--      ON DB2PROD.TS0550 (DOCUMENT_TYPE ASC, DA_BOOK_VESSEL_COM ASC, MD_OP_CU_TYPE ASC, MDC_DATE_SHIPPED ASC, FK_TS0340CLIENT ASC, FK_TS0340NUMBER ASC, RELATIVE_NUMBER ASC);
--
--  CREATE UNIQUE INDEX DB2PROD.IS055008
--      ON DB2PROD.TS0550 (FK_TS0340CLIENT ASC, DA_OP_POL ASC, FK_TS0340NUMBER ASC, RELATIVE_NUMBER ASC);
--
--  CREATE CLUSTERED UNIQUE INDEX DB2PROD.IS055007
--     ON DB2PROD.TS0550 (DOCUMENT_NO ASC, DOCUMENT_TYPE ASC, MTD_NO_SUFFIX ASC, FK_TS0340CLIENT ASC, FK_TS0340NUMBER ASC, RELATIVE_NUMBER ASC);
--
--  CREATE INDEX DB2PROD.IS055006
--      ON DB2PROD.TS0550 (DA_OP_DP_VOYAGE_NO ASC, DA_OP_POL ASC, DA_OP_POD ASC, FK_TS0340CLIENT ASC, FK_TS0340NUMBER ASC);
--
