DROP TABLE IF EXISTS TRANSPORT_TYPE;

CREATE TABLE TRANSPORT_TYPE
(
    ID              VARCHAR(36) NOT NULL PRIMARY KEY,
    NUMBER          SMALLINT    NOT NULL,
    VALID_FROM_DATE DATE        NOT NULL,
    VALID_TO_DATE   DATE        NOT NULL,
    MAIN_TYPE       ENUM ('CO', 'CU', 'MT', 'PT', 'SC'),
    MOVEMENT        ENUM ('BB', 'FCL', 'LCL'),
    SERVICE         ENUM ('CIC', 'CPC', 'CPT', 'HOU'),
    HAULAGE         ENUM ('CH', 'MH', 'MX'),
    OUTPUT_SEQ_NO   SMALLINT,
    FK_TS0360NUMBER SMALLINT,
    LAST_CHANGE     LONG        NOT NULL,
    CHANGED_BY      VARCHAR(8),
    CHANGE_LOC      VARCHAR(1)
);

-- CREATE UNIQUE INDEX IDX1_TRANSPORT_TYPE ON TRANSPORT_TYPE (MOVEMENT, SERVICE, HAULAGE, NUMBER);
-- CREATE UNIQUE INDEX IDX2_TRANSPORT_TYPE ON TRANSPORT_TYPE (MAIN_TYPE, MOVEMENT, SERVICE, HAULAGE, NUMBER);
-- CREATE INDEX IDX3_TRANSPORT_TYPE ON TRANSPORT_TYPE (FK_TS0360NUMBER);
-- CREATE UNIQUE INDEX IDX4_TRANSPORT_TYPE ON TRANSPORT_TYPE (NUMBER);
